*********************************************************************
*																  	*
*  Name: autoexec.sas											  	*
*  Description: Sets up libraries etc for the case study.			*
*																	*
*  Creation Date: 2021-08-20										*
*																	*
*********************************************************************
;


*TO EDIT;
*set this root as the location where you have saved the downloaded BUSINESS_CASE_STUDY_FC folder for this project, eg;
%let root= C:\Users\Felix\Documents\My SAS Files;
*Set this data_location as the location where the input data files are stored, eg;
%let data_location= C:\Users\Felix\Documents\My SAS Files\BUSINESS_CASE_STUDY_FC\SAS\Data\1_Input;


*SEE Run_Me.sas IN 'Programs' FOLDER TO RUN THE FULL CODE;







*DO NOT EDIT BELOW THIS POINT;

%let sas_root= &root.\BUSINESS_CASE_STUDY_FC\SAS;



*libname statements;

*could add input filename but not needed;

libname raw "&sas_root.\Data\2_Raw";
libname staging "&sas_root.\Data\3_Staging";
libname detail "&sas_root.\Data\4_Detail";
libname marts "&sas_root.\Data\5_Marts";
libname excepts "&sas_root.\Data\6_Exceptions"; *cannot name library exceptions -too long ;

libname shared "&sas_root.\Shared"; *For formats etc;

filename macros "&sas_root.\Macros";



*could set pagesize,options etc here??;
*maybe set default options eg for the outputted pdfs;


options mautosource
		sasautos=(macros sasautos)
		fmtsearch=(shared)
		nofmterr
		msglevel=i
		mcompilenote=noautocall
		nodate
		missing="";


title;
footnote;
%let today_f = %sysfunc(today(), worddate20.);*get current date for footnote;
footnote2 "Generated by &sysuserid. on &today_f. at &systime..";